services:
  web:
    image: nginx:latest
    environment:
      TZ: Asia/Tokyo
    networks:
      - my_network
    labels:
      - traefik.enable=true
      - traefik.http.routers.web.rule=Host(`web.docker.localhost`)
      # - traefik.http.routers.web.entrypoints=web
      # - traefik.http.routers.web.rule=PathPrefix(`/nginx/`)

networks:
  my_network:
    external: true